name: Deploy WebHook Server


on:
  push:
    branches:
      - 'main'
      - 'Main'

jobs:
  deploys:
    runs-on: ubuntu-latest
    stpes:
    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        docker build -t asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/tv-bot-trade/n-tv-webhook:latest .
        docker push asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/tv-bot-trade/n-tv-webhook:latest